import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Feed from '../components/Feed'
import { useContext } from 'react'
import { AuthContext } from '@/context/auth'
import { Router, useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  
  const {user} = useContext(AuthContext)

  const Redirect = ()=>{
    const router = useRouter();
    router.push('/login')
    return null;
  }

  return (
    <>
      <Head>
        <title>Reels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        user?.uid? 
        <Feed></Feed>:<Redirect/>
      }
    </>
  )
}
